### ISSUE TITLE
Various front end bugs

### ISSUE THREAD

**Issue by jessemoreburritos** [CodeforAustralia/heritage-near-me#143]
- [x] About page background. Text bg seems buggy and doesn't extend to the bottom of the text body on mobile& narrow browsers.
![image](https://cloud.githubusercontent.com/assets/16284413/18153326/1eb4c678-7040-11e6-8b38-c20d7d629a97.png)

- [ ] This still happens on mobile
![image](https://cloud.githubusercontent.com/assets/16284413/18153357/528c0e66-7040-11e6-879e-601f237e3a8c.png)

- [x] Popover alignment on map screen. Arrow is aligned to top left hand corner of site pins. 
![image](https://cloud.githubusercontent.com/assets/16284413/18152666/e7ee5168-703a-11e6-9ca0-271073c9036e.png)
Can we align it to the right of each site pin **like so** 
![image](https://cloud.githubusercontent.com/assets/16284413/18152708/4bd64910-703b-11e6-9570-ff9d2f3a2cfe.png)

**OR**

![image](https://cloud.githubusercontent.com/assets/16284413/18153287/d3e00946-703f-11e6-98ae-112fd115bc77.png)

- [ ] Swiping right heart popover appears too late & isn't recognisable. Also, nothing appears when swiping left. Can we have these appear earlier?
![image](https://cloud.githubusercontent.com/assets/16284413/18153297/ed0b58b2-703f-11e6-9658-bd433863bffd.png)

- [ ] custom loader is different on initial loading page and individual story pages. Can we have the loader seen on the welcome screen across the story page too?
![image](https://cloud.githubusercontent.com/assets/16284413/18153061/465ce87e-703e-11e6-8162-9bfc50e8731d.png)

**Welcome screen loader** 

![image](https://cloud.githubusercontent.com/assets/16284413/18153075/64f53264-703e-11e6-8f08-11a52a3a827c.png)

- [x]  Are we able to get a white background on the close button?
![image](https://cloud.githubusercontent.com/assets/16284413/18153178/1f244d46-703f-11e6-8810-3d3f4e50ac13.png)

- [x] Meow

**Comment by techieshark** [comment]
Another thing: currently if network is slow you might get a Flash of Unwanted Times New Roman Text (FOUTNRT -- I made that up but the effect is real). 

before proxima nova loads:
<img width="241" alt="screen shot 2016-09-01 at 6 11 20 pm" src="https://cloud.githubusercontent.com/assets/1072292/18160213/ba08b1c8-706f-11e6-9659-58b2f147c93a.png">

after:

![image](https://cloud.githubusercontent.com/assets/1072292/18160241/dc403004-706f-11e6-9029-526bfca2f3d5.png)

**Comment by techieshark** [comment]
Search bar styling doesn't quite work on Safari

![image](https://cloud.githubusercontent.com/assets/1072292/18161670/4484c78c-7076-11e6-8845-4585324e3630.png)

looks like Safari is happy to shrink buttons smaller than their content, unlike Chrome

**Comment by techieshark** [comment]
There's a lot here, so I'm going to submit a pull request for what I have now.

Things I'm going to leave for separate issue(s): 

* site image overflows out of map popup:

![image](https://cloud.githubusercontent.com/assets/1072292/18239266/8288c9f2-7387-11e6-8006-45a0257f7d18.png)
* "Swiping right heart popover appears too late & isn't recognisable. Also, nothing appears when swiping left. Can we have these appear earlier?"

* "custom loader is different on initial loading page and individual story pages. Can we have the loader seen on the welcome screen across the story page too?" [For now, not changing mainly because the thinking behind keeping it like this earlier was that the initial loader gives the impression we're searching nearby, while the other loader looks like a traditional "waiting for content to download" loader".]
