### ISSUE TITLE
Document the codebase

### ISSUE THREAD

**Issue by kennib** [CodeforAustralia/heritage-near-me#47]
Currently the broad overview of how the code works is in the mind of @kennib.
It needs to be written down in a more rigorous manner.

**Comment by kennib** [comment]
Issue #49 will hopefully make this issue a simpler task.

**Comment by techieshark** [comment]
Was looking into elm doc stuff today. Findings (just an fyi and putting all these links in one place):

* Elm has a code documentation format specified: http://package.elm-lang.org/help/documentation-format

* and this codebase is somewhat minimally documented, as alluded to in this issue description.

* and if you run `elm-make --docs=documentation.json` you get a file that you can stick in http://package.elm-lang.org/help/docs-preview to preview the docs in a browser rather than in a code editor.

* but there's apparently no way to generate local docs otherwise, despite being requested by others Elm users (https://github.com/elm-lang/elm-lang.org/issues/169). I've started looking at generating a docset for Dash: https://github.com/pdamoc/elm-docset/issues/9 as one solution.
